# Generated by Django 4.2 on 2023-04-22 22:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wallets", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cryptoaddress",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="cryptoaddress",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
