# Generated by Django 4.2 on 2023-04-25 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("wallets", "0003_alter_cryptoaddress_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="CryptoWallet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mnemonic", models.CharField(max_length=256)),
                (
                    "wallet_name",
                    models.CharField(max_length=128, verbose_name="Wallet name"),
                ),
            ],
        ),
        migrations.AddField(
            model_name="cryptoaddress",
            name="wallet",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="addresses",
                to="wallets.cryptowallet",
            ),
        ),
    ]
